// Copyright (c) 2016, Open DICOMweb Project. All rights reserved.
// Use of this source code is governed by the open source license
// that can be found in the LICENSE file.
// Author: Jim Philbin <jfphilbin@gmail.edu> -
// See the AUTHORS file for other contributors.

// *** This file generated by '../gen/generate_class.dart' ***
// ----------------------------------------------------------

/// DICOM Coding Scheme Designators
class CodingScheme {
  final String designator;
  final String uid;
  final String description;

  const CodingScheme(this.designator, this.uid, this.description);

static CodingScheme lookup(String designator) => map[designator];

  static const ACR = const CodingScheme("ACR", "2.16.840.1.113883.6.76", "ACR Index for Radiological Diagnosis Revised, 3rd Edition 1986");
  static const ASTM_sigpurpose = const CodingScheme("ASTM-sigpurpose", "1.2.840.10065.1.12", "ASTM E 2084 Signature Purpose codes (see Annex A1 of ASTM E 2084), ASTM Subcommittee E 31.20 Data and System Security for Health Information");
  static const BARI = const CodingScheme("BARI", "", "Bypass Angiography Revascularization Investigation, Alderman, EL and Stadius, M, Coronary Artery Disease 1992, 3:1189-1207; endorsed by ACC/AHA Guidelines for Coronary Angiography, J Am Coll Cardiol 1999, 33:1791");
  static const BI = const CodingScheme("BI", "", "ACR Breast Imaging Reporting and Data System (BI-RADS®), Coding Scheme Version (0008,0103) is required; code values are section and paragraph identifiers within the publication where the code meaning is defined (e.g., ""I.D.1"", where I = Breast Imaging Lexicon, D = Special Cases, 1 = Tubular Density, as the code value for ""Tubular Density""). Note In the HL7 registry, the abbreviation BI is assigned to a different coding scheme, specifically the Beth Israel problem list.");
  static const C4 = const CodingScheme("C4", "2.16.840.1.113883.6.12", "American Medical Association's Current Procedure Terminology 4 (CPT-4)");
  static const C5 = const CodingScheme("C5", "2.16.840.1.113883.6.82", "American Medical Association's Current Procedure Terminology 5 (CPT-5)");
  static const CD2 = const CodingScheme("CD2", "2.16.840.1.113883.6.13", "American Dental Association's (ADA) Current Dental Terminology 2 (CDT-2)");
  static const CTV3 = const CodingScheme("CTV3", "2.16.840.1.113883.6.6", "NHS Clinical Terms Version 3 (Read Codes)");
  static const DCM = const CodingScheme("DCM", "1.2.840.10008.2.16.4", "DICOM Controlled Terminology; PS3.16 Content Mapping Resource, Annex D (Note that HL7 also specifies an OID of 2.16.840.1.113883.6.31, but deprecates it in favor of 1.2.840.10008.2.16.4).");
  static const DCMUID = const CodingScheme("DCMUID", "1.2.840.10008.2.6.1", "DICOM UID Registry");
  static const FMA = const CodingScheme("FMA", "2.16.840.1.113883.6.119", "Digital Anatomist Foundational Model of Anatomy");
  static const HPC = const CodingScheme("HPC", "2.16.840.1.113883.6.14", "Healthcare Financing Administration (HCFA) Common Procedure Coding System (HCPCS)");
  static const I10 = const CodingScheme("I10", "2.16.840.1.113883.6.3", "International Classification of Diseases revision 10 (ICD-10)");
  static const I10P = const CodingScheme("I10P", "2.16.840.1.113883.6.4", "ICD-10 Procedure Coding System (ICD 10 PCS)");
  static const I9 = const CodingScheme("I9", "2.16.840.1.113883.6.42", "International Classification of Diseases revision 9 (ICD-9)");
  static const I9C = const CodingScheme("I9C", "2.16.840.1.113883.6.2", "International Classification of Diseases revision 9, with Clinical Modifications (ICD-9-CM)");
  static const IETF4646 = const CodingScheme("IETF4646", "", "RFC4646, Tags for Identifying Languages, The Internet Society (2005)");
  static const ISO639_1 = const CodingScheme("ISO639_1", "2.16.840.1.113883.6.99", "Two-letter language codes Note HL7 uses ""ISO639-1"" for the symbolic name, with a hyphen rather than an underscore");
  static const ISO639_2 = const CodingScheme("ISO639_2", "2.16.840.1.113883.6.100", "Three-letter language codes Note HL7 uses ""ISO639-2"" for the symbolic name, with a hyphen rather than an underscore");
  static const ISO3166_1 = const CodingScheme("ISO3166_1", "2.16.1", "ISO 3166-1 alpha-2 Country Codes Note HL7 uses ""ISO3166-1"" for the symbolic name, with a hyphen rather than an underscore");
  static const ISO5218_1 = const CodingScheme("ISO5218_1", "", "Representation of Human Sexes (not used - see note)");
  static const ISO_OID = const CodingScheme("ISO_OID", "", "ISO/IEC 8824-1- Information Technology - Abstract Syntax 1 (ASN.1): Specification of Basic Notation, and ISO/IEC 9834-1 - Information technology - Open Systems Interconnection - Procedures for the operation of OSI Registration Authorities: General procedures and top arcs of the ASN.1 Object Identifier tree");
  static const ITIS_TSN = const CodingScheme("ITIS_TSN", "1.2.840.10008.2.?16.?7", "A Taxonomic Serial Number (TSN) is a unique, persistent, non-intelligent identifier for a scientific name in the context of the Integrated Taxonomic Information System (ITIS). See http://?www.itis.gov.");
  static const LN = const CodingScheme("LN", "2.16.840.1.113883.6.1", "Logical Observation Identifier Names and Codes, Regenstrief Institute");
  static const MA = const CodingScheme("MA", "1.2.840.10008.2.?16.?5", "The Adult Mouse Anatomy Ontology maintained by The Jackson Laboratory. See http://?www.informatics.jax.org/?searches/?AMA.cgi??id=MA:0002405. Hayamizu TF, Mangan M, Corradi JP, Kadin JA, Ringwald M. The Adult Mouse Anatomical Dictionary: a tool for annotating and integrating data. Genome Biology 2005;6(3):R29. doi:10.1186/gb-2005-6-3-r29. http://?www.ncbi.nlm.nih.gov/?pmc/?articles/?PMC1088948/");
  static const MDC = const CodingScheme("MDC", "2.16.840.1.113883.6.24", "ISO/IEEE 11073 Medical Device Nomenclature, including all its subsections (-10101, -10102, etc.), encoded as decimal strings <partition>:<dictionary>");
  static const MDNS = const CodingScheme("MDNS", "", "Universal Medical Device (UMD) Nomenclature System");
  static const MGI = const CodingScheme("MGI", "1.2.840.10008.2.?16.?8", "The MGI ID from the Mouse Genome Initiative (MGI) nomenclature. See http://?www.informatics.jax.org/?mgihome/?nomen/.");
  static const MSH = const CodingScheme("MSH", "2.16.840.1.113883.6.177", "US National Library of Medicine (NLM) Medical Subject Headings (MeSH) See http://?www.nlm.nih.gov/?mesh/?meshhome.html.");
  static const NBD = const CodingScheme("NBD", "2.16.840.1.113883.15.2", "NASPE/BPEG Defibrillator Code Bernstein AD, et al.""The NASPE/BPEG Defibrillator Code"" PACE, 16:1776-1780, 1993");
  static const NBG = const CodingScheme("NBG", "2.16.840.1.113883.15.3", "NASPE/BPEG Generic Pacemaker Code (2000) Bernstein AD, et al.""The Revised NASPE/BPEG Generic Code for antibradycardia, adaptive-rate, and multisite pacing."" Pacing Clin Electrophysiol., 25:260-264, 2002 See http://www.hrsonline.org/Practice-Guidance/Clinical-Guidelines-Documents/?2002-The-Revised-NASPE-BPEG-Generic-Code-for-Antibradycardia-?AdaptiveRate-and-Multisite-Pacing.");
  static const NCDR = const CodingScheme("NCDR", "", "American College of Cardiology National Cardiovascular Data Registry™ Cath Lab Module Version 1.1, 1997; Version 2.0b, 1999");
  static const NCIt = const CodingScheme("NCIt", "2.16.840.1.113883.3.26.1.1", "NCI Thesaurus. See http://?ncit.nci.nih.gov/");
  static const NEU = const CodingScheme("NEU", "2.16.840.1.113883.6.210", "NeuroNames. The numeric brainInfoID is used as the code value. See http://?braininfo.rprc.washington.edu/?aboutBrainInfo.aspx#NeuroNames");
  static const NICIP = const CodingScheme("NICIP", "2.16.840.1.113883.2.1.3.2.4.21", "UK National Health Service National Interim Clinical Imaging Procedures (NICIP) Short Code (e.g., ""CCHAPC"" for CT Thorax abdomen pelvis with contrast)");
  static const NPI = const CodingScheme("NPI", "", "HCFA National Provider Identifier");
  static const POS = const CodingScheme("POS", "2.16.840.1.113883.6.50", "HCFA Place of Service (POS) Codes for Professional Claims");
  static const PUBCHEM_CID = const CodingScheme("PUBCHEM_CID", "1.2.840.10008.2.?16.?9", "US National Center for Biotechnology Information (NCBI) PubChem Compound CID. See https://?pubchem.ncbi.nlm.nih.gov/.");
  static const RADLEX = const CodingScheme("RADLEX", "2.16.840.1.113883.6.256", "RadLex");
  static const RFC3066 = const CodingScheme("RFC3066", "2.16.840.1.113883.6.121", "RFC3066, Tags for the Identification of Languages, Internet Engineering Task Force Note HL7 uses ""IETF3066"" for the symbolic name. RFC3066 has been superseded by RFC4646.");
  static const _99SDM = const CodingScheme("99SDM", "2.16.840.1.113883.6.53", "SNOMED DICOM Microglossary (Retired) (see Section 8.1)");
  static const SCPECG = const CodingScheme("SCPECG", "", "Standard Communications Protocol for Computer-Assisted Electrocardiography, Draft proposal for ISO Standard, AAMI, Revision 1.3");
  static const SNM3 = const CodingScheme("SNM3", "2.16.840.1.113883.6.51", "SNOMED International Version 3 (see Section 8.1)");
  static const SCT = const CodingScheme("SCT", "2.16.840.1.113883.6.96", "SNOMED-CT, using the CT code values");
  static const SRT = const CodingScheme("SRT", "2.16.840.1.113883.6.96", "SNOMED-CT, using the ""SNOMED-RT style"" code values (see Section 8.1) Note HL7 uses ""SNM"" for the symbolic name.");
  static const UBERON = const CodingScheme("UBERON", "1.2.840.10008.2.?16.?6", "The Uberon ID from the Uberon integrated cross-species ontology covering anatomical structures in animals. See http://?uberon.org/.");
  static const UCUM = const CodingScheme("UCUM", "2.16.840.1.113883.6.8", "Unified Code for Units of Measure");
  static const UMLS = const CodingScheme("UMLS", "2.16.840.1.113883.6.86", "UMLS codes as CUIs making up the values in a coding system");
  static const UPC = const CodingScheme("UPC", "2.16.840.1.113883.6.55", "Universal Product Code - Universal Code Council");

  static const Map<String, dynamic> uidMap = const {
    "2.16.840.1.113883.6.76": ACR,
    "1.2.840.10065.1.12": ASTM_sigpurpose,
    "2.16.840.1.113883.6.12": C4,
    "2.16.840.1.113883.6.82": C5,
    "2.16.840.1.113883.6.13": CD2,
    "2.16.840.1.113883.6.6": CTV3,
    "1.2.840.10008.2.16.4": DCM,
    "1.2.840.10008.2.6.1": DCMUID,
    "2.16.840.1.113883.6.119": FMA,
    "2.16.840.1.113883.6.14": HPC,
    "2.16.840.1.113883.6.3": I10,
    "2.16.840.1.113883.6.4": I10P,
    "2.16.840.1.113883.6.42": I9,
    "2.16.840.1.113883.6.2": I9C,
    "2.16.840.1.113883.6.99": ISO639_1,
    "2.16.840.1.113883.6.100": ISO639_2,
    "2.16.1": ISO3166_1,
    "1.2.840.10008.2.?16.?7": ITIS_TSN,
    "2.16.840.1.113883.6.1": LN,
    "1.2.840.10008.2.?16.?5": MA,
    "2.16.840.1.113883.6.24": MDC,
    "1.2.840.10008.2.?16.?8": MGI,
    "2.16.840.1.113883.6.177": MSH,
    "2.16.840.1.113883.15.2": NBD,
    "2.16.840.1.113883.15.3": NBG,
    "2.16.840.1.113883.3.26.1.1": NCIt,
    "2.16.840.1.113883.6.210": NEU,
    "2.16.840.1.113883.2.1.3.2.4.21": NICIP,
    "2.16.840.1.113883.6.50": POS,
    "1.2.840.10008.2.?16.?9": PUBCHEM_CID,
    "2.16.840.1.113883.6.256": RADLEX,
    "2.16.840.1.113883.6.121": RFC3066,
    "2.16.840.1.113883.6.53": _99SDM,
    "2.16.840.1.113883.6.51": SNM3,
    //TODO: fix - two coding schemes share the same Uid.
    //"2.16.840.1.113883.6.96": SCT,
    "2.16.840.1.113883.6.96": const [SRT, SCT],
    "1.2.840.10008.2.?16.?6": UBERON,
    "2.16.840.1.113883.6.8": UCUM,
    "2.16.840.1.113883.6.86": UMLS,
    "2.16.840.1.113883.6.55": UPC};

  static const Map<String, CodingScheme> map = const {
    "ACR": ACR,
    "ASTM-sigpurpose": ASTM_sigpurpose,
    "BARI": BARI,
    "BI": BI,
    "C4": C4,
    "C5": C5,
    "CD2": CD2,
    "CTV3": CTV3,
    "DCM": DCM,
    "DCMUID": DCMUID,
    "FMA": FMA,
    "HPC": HPC,
    "I10": I10,
    "I10P": I10P,
    "I9": I9,
    "I9C": I9C,
    "IETF4646": IETF4646,
    "ISO639_1": ISO639_1,
    "ISO639_2": ISO639_2,
    "ISO3166_1": ISO3166_1,
    "ISO5218_1": ISO5218_1,
    "ISO_OID": ISO_OID,
    "ITIS_TSN": ITIS_TSN,
    "LN": LN,
    "MA": MA,
    "MDC": MDC,
    "MDNS": MDNS,
    "MGI": MGI,
    "MSH": MSH,
    "NBD": NBD,
    "NBG": NBG,
    "NCDR": NCDR,
    "NCIt": NCIt,
    "NEU": NEU,
    "NICIP": NICIP,
    "NPI": NPI,
    "POS": POS,
    "PUBCHEM_CID": PUBCHEM_CID,
    "RADLEX": RADLEX,
    "RFC3066": RFC3066,
    "99SDM": _99SDM,
    "SCPECG": SCPECG,
    "SNM3": SNM3,
    "SCT": SCT,
    "SRT": SRT,
    "UBERON": UBERON,
    "UCUM": UCUM,
    "UMLS": UMLS,
    "UPC": UPC};

  static const List<String> tags = const [
    "ACR",
    "ASTM-sigpurpose",
    "BARI",
    "BI",
    "C4",
    "C5",
    "CD2",
    "CTV3",
    "DCM",
    "DCMUID",
    "FMA",
    "HPC",
    "I10",
    "I10P",
    "I9",
    "I9C",
    "IETF4646",
    "ISO639_1",
    "ISO639_2",
    "ISO3166_1",
    "ISO5218_1",
    "ISO_OID",
    "ITIS_TSN",
    "LN",
    "MA",
    "MDC",
    "MDNS",
    "MGI",
    "MSH",
    "NBD",
    "NBG",
    "NCDR",
    "NCIt",
    "NEU",
    "NICIP",
    "NPI",
    "POS",
    "PUBCHEM_CID",
    "RADLEX",
    "RFC3066",
    "99SDM",
    "SCPECG",
    "SNM3",
    "SCT",
    "SRT",
    "UBERON",
    "UCUM",
    "UMLS",
    "UPC"];

  static const List<String> actions = const [
    ACR,
    ASTM_sigpurpose,
    BARI,
    BI,
    C4,
    C5,
    CD2,
    CTV3,
    DCM,
    DCMUID,
    FMA,
    HPC,
    I10,
    I10P,
    I9,
    I9C,
    IETF4646,
    ISO639_1,
    ISO639_2,
    ISO3166_1,
    ISO5218_1,
    ISO_OID,
    ITIS_TSN,
    LN,
    MA,
    MDC,
    MDNS,
    MGI,
    MSH,
    NBD,
    NBG,
    NCDR,
    NCIt,
    NEU,
    NICIP,
    NPI,
    POS,
    PUBCHEM_CID,
    RADLEX,
    RFC3066,
    _99SDM,
    SCPECG,
    SNM3,
    SCT,
    SRT,
    UBERON,
    UCUM,
    UMLS,
    UPC];
}
